DROP VIEW IF EXISTS ItemsWithCategory;
DROP VIEW IF EXISTS ItemsByCategory;

DROP PROCEDURE IF EXISTS ProcessCheckout;
DROP PROCEDURE IF EXISTS ProcessWelcomeBasketCheckout;
DROP PROCEDURE IF EXISTS CheckCategoryCheckoutLimit;
DROP PROCEDURE IF EXISTS CheckInsufficientInventory;
DROP PROCEDURE IF EXISTS CheckCartItemLimit;
DROP PROCEDURE IF EXISTS LogTransaction;
DROP PROCEDURE IF EXISTS LogTransactionItem;
DROP PROCEDURE IF EXISTS GetRecentTransactions;
DROP PROCEDURE IF EXISTS VerifyVolunteerPin;
DROP PROCEDURE IF EXISTS ProcessInventoryChange;

DROP TYPE IF EXISTS CartItemsType;

DROP TABLE IF EXISTS TransactionItems; 
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS TransactionTypes;
DROP TABLE IF EXISTS Tracking; 
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Residents;
DROP TABLE IF EXISTS Units;
DROP TABLE IF EXISTS Buildings;
