USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = N'Inventory')
BEGIN
    ALTER DATABASE [Inventory] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [Inventory];
END
GO

CREATE DATABASE [Inventory];
GO
