DELETE FROM Items;
GO

INSERT INTO Items (name, type, category_id, quantity, low, medium, description) VALUES
('Adult absorbent underwear', 'General', 10, 87, 9, 15, 'Diapers'),
('Baby Wipes', 'General', 10, 8, 6, 20, 'Flushable wipes, body wipes, face wipes'),
('Body lotion', 'General', 10, 0, 7, 29, 'Body moisturizer'),
('Body soap', 'General', 10, 871, 2, 25, 'Bar soap, body wash, body scrub'),
('Chapstick', 'General', 10, 61, 6, 24, ''),
('Comb / hair brush', 'General', 10, 29, 4, 17, ''),
('Conditioner', 'General', 10, 13, 3, 21, ''),
('Deodorant', 'General', 10, 80, 5, 27, 'anti-persperant'),
('Face lotion', 'General', 10, 0, 7, 22, 'Face moisturizer'),
('Face Masks', 'General', 10, 12, 8, 28, ''),
('Face Tissue', 'General', 10, 57, 3, 27, 'Kleenex'),
('Face wash', 'General', 10, 8, 8, 11, 'Face cleanser'),
('Feminine Hygiene Kit', 'General', 10, 91, 1, 23, 'Tampons, pads, feminine hygiene product, menstrual products, period products'),
('First aid Kit', 'General', 10, 52, 9, 30, 'Contains band aids, gauze, neosporin, wrap'),
('Floss', 'General', 10, 137, 7, 21, 'Floss picks, string floss'),
('Gauze', 'General', 10, 23, 9, 17, 'Gauze, wrap'),
('Hair Accessory', 'General', 10, 83, 3, 21, 'Scrunchie, hair tie, hair clip, bonnet, barrette, bobby pin'),
('Hair gel', 'General', 10, 6, 2, 24, 'hair grease, hold gel, twist gel, pomade'),
('Hair Tool', 'General', 10, 6, 7, 15, 'Curling iron, hair dryer, hair straightener, shampoo brush, blow dryer, clippers, electric razor'),
('Hygiene Kit', 'General', 10, 7, 8, 21, 'Contains multiple items of personal care that are bagged/bundled together'),
('Loofah', 'General', 10, 10, 2, 28, ''),
('Nail Care', 'General', 10, 50, 1, 13, 'Nail clippers, nail file, cuticle clippers, nail polish, toe nail clippers'),
('Personal Care Miscellaneous', 'General', 10, 259, 7, 15, 'Anything not otherwise listed: hand sanitizer and makeup'),
('Shampoo', 'General', 10, 35, 9, 16, ''),
('Shaving / Razors', 'General', 10, 91, 5, 11, 'Shaving cream'),
('Toilet paper', 'General', 10, 57, 10, 18, ''),
('Toothbrush', 'General', 10, 357, 2, 21, ''),
('Toothpaste', 'General', 10, 37, 3, 27, ''),
('Vaseline', 'General', 10, 21, 1, 22, ''),
('Art Kit', 'General', 4, 1, 4, 13, 'Items that are an entire art experience in one package'),
('Bag', 'General', 4, 5, 5, 20, 'Backpack, purse, wallet, tote, suitcase, bag, tote bag, satchel, fanny pack, makeup bag'),
('Book', 'General', 4, 94, 3, 15, 'Any book that is not a cook book or coloring book'),
('Coloring Book', 'General', 4, 1, 7, 29, ''),
('Cook book', 'General', 4, 4, 10, 16, ''),
('Drawing Tools', 'General', 4, 33, 4, 16, 'Colored pencils, chalk, paint brush, crayons, markers'),
('Electronics', 'General', 4, 3, 9, 27, 'Bluetooth speaker, headphones, charging cable, alarm clock, power strip'),
('Game', 'General', 4, 21, 5, 17, 'Board game, chess, checkers'),
('Home Improvement', 'General', 4, 11, 6, 11, 'Screwdriver, hammer, measuring tape, tool'),
('Paint', 'General', 4, 5, 4, 27, ''),
('Paper / Canvas', 'General', 4, 0, 5, 23, 'Lined paper, notebook, canvas'),
('Pet food', 'General', 4, 196, 3, 11, 'Cat food, dog food, treat'),
('Pet Supplies', 'General', 4, 31, 10, 27, 'Cat litter, food bowl, water bowl, leash, collar, cat toy, dog toy'),
('Planner / Calendar', 'General', 4, 3, 7, 10, ''),
('Playing Cards', 'General', 4, 5, 8, 17, ''),
('Puzzle', 'General', 4, 24, 10, 13, ''),
('Sports / Recreation', 'General', 4, 3, 7, 14, 'Camping gear, picnic blanket, sleeping bag, fishing, weights, yoga mat, bat and ball, outdoor activities, exercise equipment, workout gear, sport'),
('Baking Pan / dish', 'General', 3, 0, 9, 20, 'Cake pan, muffin tin, baking sheet, casserole dish, pie pan'),
('Bowl', 'General', 3, 22, 2, 13, 'Cereal bowl, soup bowl, snack bowl, salad bowl, dinner bowl'),
('Can opener', 'General', 3, 5, 8, 16, ''),
('Cooking Spoon', 'General', 3, 41, 10, 27, 'Large spoon, wooden spoon, metal spoon, plastic spoon, slotted spoon'),
('Cup', 'General', 3, 76, 4, 22, 'Drinking glass'),
('Cutting board', 'General', 3, 39, 10, 29, ''),
('Dish towel', 'General', 3, 253, 3, 22, 'Kitchen towel, rag, tea towel'),
('Silverware Set ', 'General', 3, 9, 2, 24, 'Flatware set, fork set, spoon set, butter knife set, any bundles of silverware'),
('Frying pan', 'General', 3, 6, 9, 30, 'Skillet, wok, castiron'),
('Kitchen Miscellaneous', 'General', 3, 6, 7, 27, 'Anything not otherwise listed: milk frother, rice cooker, apple slicer, food scale, funnel, mocha pot, aeropress, french press, paper towel holder'),
('Kitchen Scissors', 'General', 3, 1, 7, 12, ''),
('Knife', 'General', 3, 12, 1, 10, 'Kitchen knife, steak knife, knife set, chef''s knife, cleaver'),
('Ladle', 'General', 3, 8, 4, 16, ''),
('Measuring Cup', 'General', 3, 13, 3, 11, ''),
('Measuring spoon set', 'General', 3, 17, 10, 20, ''),
('Mixing bowl', 'General', 3, 11, 6, 25, 'very large bowl'),
('Mug', 'General', 3, 107, 7, 18, ''),
('Oven mitt', 'General', 3, 12, 7, 28, 'Pot holder'),
('Pasta Spoon', 'General', 3, 7, 9, 20, ''),
('Plate', 'General', 3, 197, 4, 26, 'Dinner plate, salad plate, saucer'),
('Pot', 'General', 3, 0, 7, 15, 'Sauce pan, stock pot'),
('Potato Peeler', 'General', 3, 16, 7, 17, 'Vegetable peeler'),
('Reusable waterbottle', 'General', 3, 10, 4, 12, ''),
('Spatula', 'General', 3, 11, 5, 21, 'Metal spatula, wooden spatula, rubber spatula'),
('Strainer', 'General', 3, 5, 9, 29, 'Collander'),
('Thermos', 'General', 3, 22, 10, 26, 'Travel mug, hot liquid container, tumbler '),
('Tongs', 'General', 3, 10, 3, 11, ''),
('Tupperware', 'General', 3, 100, 1, 21, ''),
('Whisk', 'General', 3, 8, 3, 28, ''),
('Coat / Jacket', 'General', 13, 82, 3, 22, ''),
('Clothing Rack', 'General', 1, 0, 10, 16, 'To hang clothes on that stands alone'),
('Curtain Rods', 'General', 1, 15, 1, 24, ''),
('Curtains', 'General', 1, 2, 6, 26, ''),
('Desk Organizer', 'General', 1, 5, 2, 25, 'Basket, bin, pen organizer'),
('Fan', 'General', 1, 0, 4, 18, 'plugs in'),
('Hanger set', 'General', 1, 7, 2, 25, 'Clothes hangers'),
('Hanging Hooks', 'General', 1, 2, 8, 14, ''),
('Hanging Organizer', 'General', 1, 0, 4, 13, 'Organizer that can hang on doors or in closets'),
('Home Goods Miscellaneous', 'General', 1, 0, 7, 13, ''),
('Kitchen Organizer', 'General', 1, 1, 7, 18, 'Drawer organizer, silverware organizer'),
('Lamp', 'General', 1, 2, 2, 10, 'desk lamp, side table lamp'),
('Large Organizer', 'General', 1, 0, 7, 26, 'Large bin, plastic drawer unit'),
('Large trash bin 7 gallon or more', 'General', 1, 1, 8, 24, ''),
('Laundry basket', 'General', 1, 8, 2, 12, 'Hamper, clothing bin'),
('Mirror', 'General', 1, 0, 4, 20, 'Standing mirror'),
('Rug', 'General', 1, 1, 6, 15, 'Welcome Mat'),
('Side Table', 'General', 1, 1, 10, 17, 'Nightstand, small table'),
('Wall Shelf', 'General', 1, 1, 7, 12, 'Has to be mounted to the wall'),
('Narcan / Syringe', 'General', 7, 33, 6, 29, ''),
('Naloxone', 'General', 7, 25, 1, 19, 'Nasal spray'),
('Test Strips', 'General', 7, 100, 8, 29, 'Drug test strips'),
('Belt', 'General', 12, 1, 9, 25, ''),
('Beanie / Hat', 'General', 12, 25, 5, 13, ''),
('Bikini Underwear', 'General', 12, 62, 2, 11, 'Womens Underwear'),
('Boxer Briefs', 'General', 12, 22, 8, 23, 'Mens Underwear'),
('Bra', 'General', 12, 25, 4, 20, ''),
('Gloves', 'General', 12, 62, 7, 10, 'Mittens'),
('Scarf', 'General', 12, 30, 10, 22, 'Gaiter'),
('Slippers', 'General', 12, 23, 8, 12, ''),
('Socks', 'General', 12, 339, 3, 14, ''),
('Bars', 'General', 6, 19, 9, 17, 'Breakfast bar, granola bar, energy bar, protein bar'),
('Misc Food Item', 'General', 6, -2, 1, 22, 'Anything not already listed like pancake mix, condiments, '),
('Beverage / Drink Mix', 'General', 6, 54, 6, 14, 'Milk, protein shake, juice, drink mix, crystal light packets, crystal light, lemonade mix'),
('Cereal', 'General', 6, 41, 7, 24, 'Oatmeal, hot cereal, cold cereal'),
('Coffee', 'General', 6, 1, 1, 13, 'Ground coffee beans, coffee beans, tea'),
('Cooking Oil', 'General', 6, 1, 6, 27, 'Avocado oil, olive oil, vegetable oil, cooking spray, crisco'),
('Fruit', 'General', 6, 33, 10, 19, 'Mandarin oranges, apple sauce, pineapple, dried fruit'),
('Meal', 'General', 6, 175, 3, 21, '"One pot": mac n cheese, ramen, chef boyardi, chili, soup'),
('Meat', 'General', 6, 51, 8, 25, 'Chicken, tuna, spam, fish'),
('Pasta / Rice', 'General', 6, 45, 6, 14, 'Pastaroni, ricearoni, noodles, spaghetti'),
('Pasta Sauce', 'General', 6, 5, 7, 30, 'Marinara sauce, alfredo sauce'),
('Seasoning', 'General', 6, 4, 9, 23, 'salt and pepper, garlic powder'),
('Vegetables', 'General', 6, 96, 4, 19, 'Potatoes, tomatoes, corn, green beans, beans of any kind'),
('Home Decor Miscellaneous', 'General', 9, 117, 5, 28, 'Frame, wall art, fake plant, planter, vase, holiday decor'),
('Broom/dustpan', 'General', 11, 4, 4, 24, 'sweeping tools'),
('Cleaner', 'General', 11, 41, 3, 20, 'All purpose cleaning spray, cleaning powder, toilet bowl cleaner, glass cleaner, disinfectant spray'),
('Cleaning Miscellaneous', 'General', 11, 0, 2, 16, 'Anything not listed'),
('Dish soap', 'General', 11, 0, 5, 25, 'Dishwashing liquid, dawn, palmolive'),
('Disinfectant Wipes', 'General', 11, 4, 6, 30, 'Clorox wipes, lysol wipes, cleaning wipes'),
('Fabric Softener / Dryer Sheets', 'General', 11, 0, 5, 16, 'bounce'),
('Hand Soap', 'General', 11, 3, 3, 21, 'Hand wash'),
('Laundry detergent', 'General', 11, 1, 5, 22, 'Laundry soap, laundry pods, laundry sheets, detergent sheets'),
('Paper towel', 'General', 11, 3, 6, 28, ''),
('Sponge', 'General', 11, 16, 5, 29, 'Scrubber, mr clean eraser'),
('Swiffer / mop & bucket', 'General', 11, 0, 6, 30, ''),
('Swiffer Refill', 'General', 11, 5, 10, 23, ''),
('Trash bags', 'General', 11, 0, 9, 21, 'Garbage bags, trash refill bags'),
('Ziplock bags', 'General', 11, 1, 2, 25, 'sandwich bags, '),
('Bed Pillow', 'General', 8, 2, 2, 22, 'Sleeping pillow'),
('Blanket', 'General', 8, 6, 9, 11, 'Throw blanket, lap blanket'),
('Comforter / Comforter Set', 'General', 8, 9, 9, 28, 'Comforter, duvet cover, duvet insert, quilt, bed spread'),
('Decorative Pillow', 'General', 8, 0, 1, 20, 'Cushion, plushie, squishmallow'),
('Mattress protector - full', 'General', 8, 1, 7, 25, ''),
('Mattress protector - twin', 'General', 8, 2, 6, 22, ''),
('Pillow Case', 'General', 8, 29, 1, 30, ''),
('Sheets - Full', 'General', 8, 3, 4, 27, ''),
('Sheets - Twin', 'General', 8, 14, 6, 19, ''),
('Bath mat', 'General', 5, 3, 4, 10, 'Shower mat'),
('Bath towel', 'General', 5, 4, 4, 17, 'Body towel'),
('Bathroom Miscellaneous', 'General', 5, 2, 6, 25, 'Anything not listed, toothbrush holder, soap dispenser, hand towel holder'),
('Hand Towel', 'General', 5, 7, 7, 26, 'bathroom towel'),
('Plunger', 'General', 5, 0, 10, 22, ''),
('Shower curtain', 'General', 5, 15, 8, 19, 'shower liner, shower curtain liner'),
('Shower curtain rings', 'General', 5, 32, 10, 20, ''),
('Small Trash bin < 4 gallons', 'General', 5, 24, 2, 21, ''),
('Toilet brush', 'General', 5, 5, 7, 13, ''),
('Washcloth', 'General', 5, 117, 10, 22, 'face cloth'),
('Coffee pot', 'General', 2, 0, 10, 12, 'keurig, nespresso'),
('Crockpot', 'General', 2, 0, 1, 11, 'Slow cooker, pressure cooker'),
('Hand Vacuum', 'General', 2, 0, 5, 20, ''),
('Microwave', 'General', 2, 0, 7, 21, ''),
('Tea Kettle', 'General', 2, 0, 3, 25, 'Electric tea kettle'),
('Television', 'General', 2, 0, 7, 27, ''),
('Toaster / Toaster Oven', 'General', 2, 3, 4, 22, ''),
('Appliance Miscellaneous', 'General', 2, 0, 1, 25, 'Waffle maker, blender, rice cooker, air fryer');
GO
